############################################################
# -*- coding: utf-8 -*-
#
#       #   #  #   #   #    #
#      ##  ##  #  ##  #    #
#     # # # #  # # # #    #  #
#    #  ##  #  ##  ##    ######
#   #   #   #  #   #       #
#
# Installer for MountWizzard4
#
# a Python-based Tool for interaction with the
# 10micron mounts GUI with PyQT5/6
#
# written in python3, (c) 2019-2024 by mworion
# Licence APL2.0
#
###########################################################

name: build_startup

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

env:
  branch: 'main'

on:
  push:
    # Run this action on the trigger event when specific files are touched
    paths:
      - '.github/workflows/build_startup.yml'
      - 'startup/**'

jobs:
  build_zip_archive:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{env.branch}}
          
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12
          
      - name: build_artifact
        run: |
          python3 -m zipapp startup -o support/startup.pyz
          cd support
          ls -la
          python3 -m zipfile -c startup_package.zip startup.pyz mw4.ico mw4.png MountWizzard4.desktop
          ls -la

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'build startup artifact'
